# Generated by Django 5.0.6 on 2024-06-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_destinations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='location',
            new_name='district',
        ),
        migrations.AddField(
            model_name='destination',
            name='state',
            field=models.CharField(default=11111, max_length=100),
            preserve_default=False,
        ),
    ]
